const data = [
  {
    name: "Addidas",
    slug: "free-shirt",
    image: "/image.avif",
    brand: "Addidas",
    price: 500,
    description: "New trend",
    category: "Shirts",
    rating: 7.3,
    numOfReviews: 5,
    countInStock: 20,
    isFeatured: true,
    banner: "/image.avif",
  },
  {
    name: "Addidas",
    slug: "free-shirt1",
    image: "/image.avif",
    brand: "Addidas",
    price: 500,
    description: "New trend",
    category: "Shirts",
    rating: 7.3,
    numOfReviews: 5,
    countInStock: 0,
    isFeatured: true,
    banner: "/image.avif",
  },
  {
    name: "Addidas",
    slug: "free-shirt2",
    image: "/image.avif",
    brand: "Addidas",
    price: 500,
    description: "New trend",
    category: "Shirts",
    rating: 7.3,
    numOfReviews: 5,
    countInStock: 20,
    isFeatured: true,
    banner: "/image.avif",
  },
  {
    name: "Addidas",
    slug: "free-shirt3",
    image: "/image.avif",
    brand: "Addidas",
    price: 500,
    description: "New trend",
    category: "Shirts",
    rating: 7.3,
    numOfReviews: 5,
    countInStock: 20,
    isFeatured: true,
    banner: "/image.avif",
  },
  {
    name: "Addidas",
    slug: "free-shirt3",
    image: "/image.avif",
    brand: "Addidas",
    price: 500,
    description: "New trend",
    category: "Shirts",
    rating: 7.3,
    numOfReviews: 5,
    countInStock: 20,
    isFeatured: true,
    banner: "/image.avif",
  },
  {
    name: "nike",
    slug: "free-shirt3",
    image: "/image.avif",
    brand: "Addidas",
    price: 500,
    description: "New trend",
    category: "Shirts",
    rating: 7.3,
    numOfReviews: 5,
    countInStock: 20,
    isFeatured: true,
    banner: "/image.avif",
  },
];

export default data;
